import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "花动创意公司",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="h-screen">
        <div className="flex flex-col items-center h-screen">
          <section className="relative flex-none z-10">
            <nav className="flex flex-row justify-center gap-20 my-4 font-zhi-mang-xing text-salmon z-10">
              <Link
                className="mx-4 text-3xl font-normal tracking-wide hover:underline "
                href="#"
              >
                首页
              </Link>
              <Link
                className="mx-4 text-3xl font-normal tracking-wide hover:underline"
                href="#"
              >
                关于我们
              </Link>
              <Link
                className="mx-4 text-3xl font-normal tracking-wide hover:underline"
                href="#"
              >
                商店
              </Link>
            </nav>
          </section>

          <section className="flex-1 w-full">{children}</section>
        </div>
      </div>
    </html>
  );
}
